/////////// customSongs -> EddyJ //////////////
///// Generated by QuizCreator for 'What is that song?' /////
const questionLimit = 16;
let question = new Array();
question[0] = new Question("../audio/eddyj/ChillingStyle.mp3","Chilling Style","Try To Remember","Dummy","Yakking");
question[1] = new Question("../audio/eddyj/CupidxDio.mp3","Cupid x Dio x EddyJ","INF.02","Fabryka","Negromancy");
question[2] = new Question("../audio/eddyj/DissNaMateusza.mp3","Diss Na Mateusza","Szynka","Nut Crack","Nowa Era");
question[3] = new Question("../audio/eddyj/DontTalkToGirl.mp3","Dont Talk To Girl","Try To Remember","I Need More Bullets","Dream Girl");
question[4] = new Question("../audio/eddyj/Dummy.mp3","Dummy","Dream Girl","Dont Talk To Girl","Now Or Never","OC");
question[5] = new Question("../audio/eddyj/Fabryka.mp3","Fabryka","INF.02","Nowa Era","Now Or Never");
question[6] = new Question("../audio/eddyj/INeedMoreBullets.mp3","I Need More Bullets","Cupid x Dio x EddyJ","Like The Devil","Chilling Style");
question[7] = new Question("../audio/eddyj/Inf02.mp3","INF.02","Like The Devil","INF.03","EE.08");
question[8] = new Question("../audio/eddyj/LikeTheDevil.mp3","Like The Devil","Negromancy","Dream Girl","Try To Remember");
question[9] = new Question("../audio/eddyj/Negromancy.mp3","Negromancy","Fabryka","Diss Na Mateusza","Szynka");
question[10] = new Question("../audio/eddyj/NowOrNever.mp3","Now Or Never","Fabryka","Never Or Now","Now And Never");
question[11] = new Question("../audio/eddyj/NowaEra.mp3","Nowa Era","Era Kamienia Łupanego","Szynka","Diss Na Mateusza");
question[12] = new Question("../audio/eddyj/NutCrack.mp3","Nut Crack","Nut Era","Negromancy","Like The Devil");
question[13] = new Question("../audio/eddyj/OC.mp3","OC","AC/DC","OC/AC","CO2");
question[14] = new Question("../audio/eddyj/Szynka.mp3","Szynka","Mięso","Diss Na Mateusza","Zakład");
question[15] = new Question("../audio/eddyj/TryToRemember.mp3","Try To Remember","Try To Not Forget","Like The Devil","Dummy");
question[16] = new Question("../audio/eddyj/Yakking.mp3","Yakking","Chilling Style","Yapping","INF.02");

getRandomQuestion(questionLimit);