/////////// ARTIST PACK -> NETSKY //////////////
///// Generated by QuizCreator for 'What is that song?' /////
///// AUTHOR: Walorson //////
const questionLimit = 10;
let question = new Array();
question[0] = new Question("../audio/everyday.mp3","Everyday","Your Way","Escape","Come Alive");
question[1] = new Question("../audio/escape.mp3","Escape","Follow","Memory Lane","Never Been Before");
question[2] = new Question("../audio/memorylane.mp3","Memory Lane","Escape","Prisma","500 Days Of Summer");
question[3] = new Question("../audio/tommorowsanotherday.mp3","Tommorow's Another Day","Porcelain","Iron Heart","Memory Lane");
question[4] = new Question("../audio/porcelain.mp3","Porcelain","Iron Heart","Prisma","Gravity");
question[5] = new Question("../audio/prisma.mp3","Prisma","Rise and Shine","Memory Lane","No Beginning");
question[6] = new Question("../audio/puppy.mp3","Puppy","Come Alive","Love Has Gone","500 Days Of Summer");
question[7] = new Question("../audio/eyesclosed.mp3","Eyes Closed","Your Way","Everyday","Love Has Gone");
question[8] = new Question("../audio/nostringattached.mp3","No Strigs Attached","Your Way","Come Alive","Leave it Alone");
question[9] = new Question("../audio/500daysofsummer.mp3","500 Days Of Summer","No Strigs Attached","Come Alive","Prisma");

getRandomQuestion(questionLimit);