/////////// customSongs -> brutal //////////////
///// Generated by QuizCreator for 'What is that song?' /////
///// AUTHOR: Walorson //////
const questionLimit = 10;
let question = new Array();
question[0] = new Question("../audio/youth.mp3","Youth","Famous Prophets","So Serious","Place On Fire","Come Over","And I","Our Times");
question[1] = new Question("../audio/avecmesmecs.mp3","Avec Mes Mecs","Still Waiting","Always Around","Mon Ton Ton","Water Water","Plus Rien","Once Was One");
question[2] = new Question("../audio/andi.mp3","And I","New Orleans","Once Was One","Street Light","Our Times","Get Back","In The End of The Time");
question[3] = new Question("../audio/yellinginsleep.mp3","Yelling In Sleep","Want To Believe","Let It Go","Four More Years","Who Says","Get Back","Plus Rien");
question[4] = new Question("../audio/whosays.mp3","Who Says","Crossroads","Half of My Heart","Edge of Desire","Perfectly Lonely","Rock Angel","Our Times");
question[5] = new Question("../audio/yellitout.mp3","Yell It Out","Disappoint Your Teacher","Turning Electric","Living In The Not World","Mystery Fantasy","Rock Angel","Edge of Desire");
question[6] = new Question("../audio/anythingispossible.mp3","Anything Is Possible","Something In The Water","It's So Good","Got The Magic","Glorious","Gimme Power","Moonlight Might");
question[7] = new Question("../audio/anaelectronic.mp3","Ana Electronic","Release","Event","Anything But Words","Even If The Time Will Pass By","Sea Of Air","Plastic Soldiers");
question[8] = new Question("../audio/placeonfire.mp3","Place On Fire","Dimnesion","Sphere","Memories","We Can Dream","Octane","Virtualism");
question[9] = new Question("../audio/getback.mp3","Get Back","We Got It","Someday Believers","Don't Give a Chance","Understand","Fall Out","Through This Night");

getRandomQuestion(questionLimit);