/////////// customSongs -> extreme //////////////
///// Generated by QuizCreator for 'What is that song?' /////
///// AUTHOR: Anonymous //////
const questionLimit = 10;
let question = new Array();
question[0] = new Question("../audio/corruption.mp3","Corruption","Bisken","Stop Smoking","Basta Boi","Teach Me","Rock Angel");
question[1] = new Question("../audio/teachme.mp3","Teach Me","Why We Lose","Temptation","The Spirit","Bodys","The Sun");
question[2] = new Question("../audio/ouch.mp3","Ouch","Ludens","Sunset","High To Death","We Own The Sky","Rock Angel");
question[3] = new Question("../audio/rockangel.mp3","Rock Angel","Baby","The Sun","Eyes Closed","Twin Fantasy","In The Mood");
question[4] = new Question("../audio/louderthanwords.mp3","Louder Than Words","War","High To Death","Grim Generation","Once Was One","Ouch");
question[5] = new Question("../audio/weownthesky.mp3","We Own The Sky","Coming For You","Another Wave From You","Soon, My Friend","Cute Thing","The Sun");
question[6] = new Question("../audio/wecanmake.mp3","We Can Make The World Stop","It Don't Mean A Thing","Wolf Like Me","Louder Than Words","Sober To Death","Corruption");
question[7] = new Question("../audio/everyday.mp3","Everyday","Prisma","Eyes Closed","Our Way","The Sun","In The Mood");
question[8] = new Question("../audio/thesun.mp3","The Sun","The Woods","Cute Thing","Plastic Soldiers","Head Is A Flame","And I");
question[9] = new Question("../audio/aprilshowers.mp3","April Showers","All Night","Lone Digger","Catgroove","Slow Drag","Ouch");
question[10] = new Question("../audio/mainmenu.mp3","Beautiful Lies","Sober To Death","Bodys","Prisma","Ardent","Still Alive");

getRandomQuestion(questionLimit);