/////////// customSongs -> hardcore //////////////
///// Generated by QuizCreator for 'What is that song?' /////
///// AUTHOR: Walorson //////
const questionLimit = 10;
let question = new Array();
question[0] = new Question("../audio/sungod.mp3","Sun God","Zenith","Hole","Whirring","Doubt","Permission","Changing","Love Hour Zero");
question[1] = new Question("../audio/eveningatmaries.mp3","Evening At Maries","I Promise","Tonight","My Head Is Going Crazy","Synthetica","Jungles","Leaving Heaven","Farewell");
question[2] = new Question("../audio/brokedit.mp3","Broked It","Spades","Let's Go","Adventure Through Madness","Real Gone","Jamestown","Set The Stage","Cold Feet");
question[3] = new Question("../audio/liftyouup.mp3","Lift You Up","My Only Cure","Helping Hands","Jamestown","Keep My Head Together","Daddy Issues","Prisma","Vi");
question[4] = new Question("../audio/ontomorningstars.mp3","Onto Morning Stars","Hell No","Since Yesterday","Birth Of A Mile","Set The Stage","Fade In, Fade Out","Set Phasers To Stun","Pompeii");
question[5] = new Question("../audio/hollywood.mp3","Hollywood","I Don't Need The Sun","What Are You Kids On?","Sunblades","Nomads","Don't","Dreamers","Grim Generation");
question[6] = new Question("../audio/amethystmagic.mp3","Amethyst Magic","1000 Years","Madness","Begin","Snake Eyes","Tommy","Marching With 6","Some Men");
question[7] = new Question("../audio/alligator.mp3","Alligator","Cold Feet","Direct Me","Grow","Ethanol","Be Your Dog","Lift You Up","Beaches");
question[8] = new Question("../audio/vanquish.mp3","Vanquish","Kakashi","Illusive","Sillouhette","5th Window","Spades","Outlaw","Skope");
question[9] = new Question("../audio/spades.mp3","Spades","Stop Saying","Farewell","Eyes Closed","Birth Of A Mile","Begin","Outlaw","Direct Me");

getRandomQuestion(questionLimit);