/////////// customSongs -> hard //////////////
///// Generated by QuizCreator for 'What is that song?' /////
///// AUTHOR: Walorson //////
const questionLimit = 10;
let question = new Array();
question[0] = new Question("../audio/feelItStill.mp3","Feel it Still","Live in the Moment","Rebel just for kicks now","Runaway","Don't Wanna Know");
question[1] = new Question("../audio/dontWannaKnow.mp3","Don't Wanna Know","One More Night","Memories","Hold My Hand","She Will Be Loved");
question[2] = new Question("../audio/robinSchulzOK.mp3","OK","Sun Goes Down","Headlights","Feel it Still","Alane");
question[3] = new Question("../audio/alanWalkerTired.mp3","Tired","Faded","Spectre","Headlights","Baby Sweet");
question[4] = new Question("../audio/holdMyHand.mp3","Hold My Hand","Are you with me","OK","Baiana","Don't wanana know");
question[5] = new Question("../audio/baiana.mp3","Baiana","Getaway","OK","Teach me","Partystarter");
question[6] = new Question("../audio/changes.mp3","Changes","Hello","Living","Ain't Nobody","Baiana");
question[7] = new Question("../audio/runaway.mp3","Runaway","And I","Feel it still","Headlights","Memories");
question[8] = new Question("../audio/lacintura.mp3","La cintura","Sofia","Oxígeno","El Mismo Sol","OK");
question[9] = new Question("../audio/ifollowrivers.mp3","I Follow Rivers","Little Bit","Possibility","Teach me","Tired");

getRandomQuestion(questionLimit);