/////////// customSongs -> veryHard //////////////
///// Generated by QuizCreator for 'What is that song?' /////
///// AUTHOR: Walorson //////
const questionLimit = 10;
let question = new Array();
question[0] = new Question("../audio/tonguetied.mp3","Tongue Tied","Raspberry","Ways to go","Party Starter","Goodbye");
question[1] = new Question("../audio/liveinthemoment.mp3","Live In The Moment","High Hopes","Number One","Keep one","Closer");
question[2] = new Question("../audio/tonight.mp3","Tonight","So Young","Crazy In Love","Forget You","Heartbreak Anthem");
question[3] = new Question("../audio/heartbreakanthem.mp3","Heartbreak Anthem","Fading Like a Flower","Pharmacy","Cinema","Perdoname");
question[4] = new Question("../audio/highenough.mp3","High Enough","Let's Go!","Closer","Lock Me Up","Be With You");
question[5] = new Question("../audio/closer2.mp3","Closer","Everytime","Runaway","Powerful Dance","Live In The Moment");
question[6] = new Question("../audio/perdoname.mp3","Perdoname","Five Hours","Cosa Fai","Let's Go!","El Mismo Sol");
question[7] = new Question("../audio/letsgo.mp3","Let's Go!","Mortals","My Heart","Cradles","Light It Up");
question[8] = new Question("../audio/youmakeme.mp3","You Make Me","Addicted To You","Lonely Together","My Heart","Closer");
question[9] = new Question("../audio/oblivion.mp3","Oblivion","Skyrim","Morowind","For A Better Day","Rise Up");
question[10] = new Question("../audio/ludens.mp3","Ludens","Broken Arrows","Everytime","Live In The Moment","Tongue Tied");

getRandomQuestion(questionLimit);