/////////// customSongs -> Minecraft Songs //////////////
///// Generated by QuizCreator for 'What is that song?' /////
const questionLimit = 3;
let question = new Array();
question[0] = new Question("audio/BurnItDown.mp3","Burn it Down","Minecraft Breakdance","Holywood siema","End of sun");
question[1] = new Question("audio/HelpLoseMyMind.mp3","Help lose my mind","Don't help lose my mind","Everything you see","Wilhelm12","Krzysztof Krawczyk - Jebać PIS");
question[2] = new Question("audio/Kotleti.mp3","Yeti Kotleti","Uciekliśmy z wyspy");

getRandomQuestion(questionLimit);