/////////// customSongs -> Example //////////////
///// Generated by QuizCreator for 'What is that song?' /////
const questionLimit = 3;
let question = new Array();
question[0] = new Question("audio/BurnItDown.mp3","Burn It Down","World of Warcraft","Symfonia C++","Numb");
question[1] = new Question("audio/Kotleti.mp3","Yeti Kotleti","Uciekliśmy z wyspy");
question[2] = new Question("audio/HelpLoseMyMind.mp3","Help Lose my Mind","Don't Help Lose my Mind","Szpaku - Młody 2pac","Justin Bieber - Baby","Krzysztof Krawczyk - Łaka maka dance");

getRandomQuestion(questionLimit);